import Link from "next/link";

export const metadata = {
  title: "About Us | Create Next App",
  description: "About | Generated by create next app",
};

export default function AboutLayout({ children }) {
  console.log("about console");
  return (
    <div className="mt-5 mb-5">
      <nav>
        <ul className="flex gap-5">
          <li>
            <Link href="/about/mission">mission</Link>
          </li>
          <li>
            <Link href="/about/vission">vission</Link>
          </li>
        </ul>
      </nav>
      <div>{children}</div>
    </div>
  );
}
